---
- name: "copy authorized_key"
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: "add nginx repo"
  yum_repository:
    name: nginx
    description: nginx centos 7
    baseurl: http://nginx.org/packages/centos/7/$basearch/
    gpgkey: https://nginx.org/keys/nginx_signing.key
    gpgcheck: yes

- name: "install necessary packages"
  yum:
    name: "{{ item }}"
  with_items:
    - nginx
