---
- name: 'restart sshd'
  service:
    name: sshd
    state: restarted

- name: 'restart firewalld'
  service:
    name: firewalld
    state: restarted

- name: "restart nginx"
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: "restart php-fpm"
  service:
    name: php-fpm
    state: restarted
    enabled: yes

- name: "restart knot"
  service:
    name: knot
    state: restarted
    enabled: yes

